version: '3.1'

services:
  db:
    image: postgres:15
    container_name: postgres15
    volumes:
      - ./local/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

